version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=grouper
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - APP_PORT=3000
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy

  database:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    # volumes:
    #   - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=grouper
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d grouper"]
      interval: 5s
      timeout: 3s
      retries: 3

  cache:
    image: redis:6-alpine
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
