name: Lint Workflow

on:
  workflow_call:
    inputs:
      bun-version:
        description: The version of Bun to use
        type: string
        required: true
        default: "1.1.7"

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ inputs.bun-version }}
      - run: bun install
      - run: bun run lint:ci
