name: Lint Workflow

on:
  workflow_call:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.1.1"
      - run: bun install
      - run: bun run lint:ci
