name: Main CI/CD
on: [push]
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      bun-version: "1.1.7"
  test:
    needs: lint
    uses: ./.github/workflows/test.yml
    with:
      bun-version: "1.1.7"
  e2e:
    needs: test
    uses: ./.github/workflows/e2e.yml
    with:
      bun-version: "1.1.7"
