name: Test Workflow

on:
  workflow_call:
    inputs:
      bun-version:
        description: The version of Bun to use
        type: string
        required: true
        default: "1.1.7"

jobs:
  integration:
    services:
      postgres16:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ inputs.bun-version }}
      - run: bun install
      - run: bun run test:integration

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ inputs.bun-version }}
      - run: bun install
      - run: bun run test:unit
